//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.TS3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Name", Namespace="http://schemas.datacontract.org/2004/07/Common.Poco")]
    [System.SerializableAttribute()]
    public partial class Name : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HebrewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGoogleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((object.ReferenceEquals(this.DateCreatedField, value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateUpdated {
            get {
                return this.DateUpdatedField;
            }
            set {
                if ((object.ReferenceEquals(this.DateUpdatedField, value) != true)) {
                    this.DateUpdatedField = value;
                    this.RaisePropertyChanged("DateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string English {
            get {
                return this.EnglishField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishField, value) != true)) {
                    this.EnglishField = value;
                    this.RaisePropertyChanged("English");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hebrew {
            get {
                return this.HebrewField;
            }
            set {
                if ((object.ReferenceEquals(this.HebrewField, value) != true)) {
                    this.HebrewField = value;
                    this.RaisePropertyChanged("Hebrew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGoogle {
            get {
                return this.IsGoogleField;
            }
            set {
                if ((this.IsGoogleField.Equals(value) != true)) {
                    this.IsGoogleField = value;
                    this.RaisePropertyChanged("IsGoogle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TS3.ITranslatorService")]
    public interface ITranslatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorService/Translate", ReplyAction="http://tempuri.org/ITranslatorService/TranslateResponse")]
        TestClient.TS3.Name Translate(string HebrewText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslatorService/Translate", ReplyAction="http://tempuri.org/ITranslatorService/TranslateResponse")]
        System.Threading.Tasks.Task<TestClient.TS3.Name> TranslateAsync(string HebrewText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranslatorServiceChannel : TestClient.TS3.ITranslatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslatorServiceClient : System.ServiceModel.ClientBase<TestClient.TS3.ITranslatorService>, TestClient.TS3.ITranslatorService {
        
        public TranslatorServiceClient() {
        }
        
        public TranslatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestClient.TS3.Name Translate(string HebrewText) {
            return base.Channel.Translate(HebrewText);
        }
        
        public System.Threading.Tasks.Task<TestClient.TS3.Name> TranslateAsync(string HebrewText) {
            return base.Channel.TranslateAsync(HebrewText);
        }
    }
}
